apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vector-search
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vector-search
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: vector-search
          image: harbor.nadileaf.com/ml-model/vs:cpu-1.0.1
          imagePullPolicy: Always
          env:
          - name: MY_DEV_ENV
            value: "product"
          - name: REDIS_HOST
              value: "text2sql-redis"
                - name: REDIS_PORT
                    value: "6379"

          resources:
            requests:
              cpu: "4"
              memory: 16Gi
            limits:
              cpu: "16"
              memory: 16Gi

          command:
            - bash
            - -c
            - |
              python /code/vector-search/server.py > /data/vector-search/log/server.log 2>&1
      imagePullSecrets:
        - name: harbor-pull-secret