apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vector-search
spec:
  serviceName: vector-search
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vector-search
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vector-search
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      nodeSelector:
        mesoor.com/component: ml-cpu
      containers:
        - name: vector-search
          image: harbor.nadileaf.com/ml-model/vs:cpu-1.1.5-py38
          imagePullPolicy: Always
          env:
          - name: MY_DEV_ENV
            value: "test"

          resources:
            requests:
              cpu: "2"
              memory: 8Gi
            limits:
              cpu: "16"
              memory: 16Gi

          volumeMounts:
            - name: vector-search-db
              mountPath: /data

          command:
            - bash
            - -c
            - |
              python /code/vector-search/vs/server.py >> /data/server.log 2>&1

      imagePullSecrets:
        - name: harbor-pull-secret
  volumeClaimTemplates:
    - metadata:
        name: vector-search-db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: "20Gi"