apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vector-search
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vector-search
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vector-search
      annotations:
        sidecar.istio.io/inject: "false"
    spec:
      nodeSelector:
        mesoor.com/component: ml-cpu
      containers:
        - name: vector-search
          image: harbor.nadileaf.com/ml-model/vs:cpu-1.0.1
          imagePullPolicy: Always
          env:
          - name: MY_DEV_ENV
            value: "test"
          - name: REDIS_HOST
            value: "text2sql-redis"
          - name: REDIS_PORT
            value: "6379"

          resources:
            requests:
              cpu: "1"
              memory: 8Gi
            limits:
              cpu: "16"
              memory: 16Gi

          command:
            - bash
            - -c
            - |
              python /code/vector-search/server.py > /data/vector-search/logs/server.log 2>&1
          volumeMounts:
            - name: vector-search-db
              mountPath: /data
      imagePullSecrets:
        - name: harbor-pull-secret
  volumeClaimTemplates:
    - metadata:
        name: vector-search-db
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: "20Gi"