apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-search
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: vector-search
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vector-search
    spec:
      containers:
        - name: vector-search
          image: harbor.nadileaf.com/ml-model/vs:cpu-1.0.1