kind: Service
apiVersion: v1
metadata:
  name: vector-search
spec:
  selector:
    app.kubernetes.io/name: vector-search
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
